apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportstatus
  labels:
    app: reportstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportstatus
  template:
    metadata:
      labels:
        app: reportstatus
    spec:
      containers:
        - name: reportstatus
          image: "username/reportstatus:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
