server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: lostreport
          uri: http://localhost:8082
          predicates:
            - Path=/lostReports/**, /분실폰조회/**
        - id: kt
          uri: http://localhost:8083
          predicates:
            - Path=/teleServices/**, 
        - id: member
          uri: http://localhost:8084
          predicates:
            - Path=/members/**, 
        - id: 보험청구
          uri: http://localhost:8085
          predicates:
            - Path=/보험청구/**, 
        - id: reportstatus
          uri: http://localhost:8086
          predicates:
            - Path=, /dashboards/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: lostreport
          uri: http://lostreport:8080
          predicates:
            - Path=/lostReports/**, 
        - id: kt
          uri: http://kt:8080
          predicates:
            - Path=/teleServices/**, 
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: 보험청구
          uri: http://보험청구:8080
          predicates:
            - Path=/보험청구/**, 
        - id: reportstatus
          uri: http://reportstatus:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
