---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostreport
  labels:
    app: lostreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostreport
  template:
    metadata:
      labels:
        app: lostreport
    spec:
      containers:
        - name: lostreport
          image: username/lostreport:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt
  labels:
    app: kt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kt
  template:
    metadata:
      labels:
        app: kt
    spec:
      containers:
        - name: kt
          image: username/kt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: username/member:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 보험청구
  labels:
    app: 보험청구
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 보험청구
  template:
    metadata:
      labels:
        app: 보험청구
    spec:
      containers:
        - name: 보험청구
          image: username/보험청구:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportstatus
  labels:
    app: reportstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportstatus
  template:
    metadata:
      labels:
        app: reportstatus
    spec:
      containers:
        - name: reportstatus
          image: username/reportstatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: lostreport
  labels:
    app: lostreport
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lostreport


---


apiVersion: v1
kind: Service
metadata:
  name: kt
  labels:
    app: kt
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kt


---


apiVersion: v1
kind: Service
metadata:
  name: member
  labels:
    app: member
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: member


---


apiVersion: v1
kind: Service
metadata:
  name: 보험청구
  labels:
    app: 보험청구
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 보험청구


---


apiVersion: v1
kind: Service
metadata:
  name: reportstatus
  labels:
    app: reportstatus
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reportstatus

